import type { CtaContent, HeroContent, LocalizedPageContent, PageMeta, SectionHeadingContent } from "./types";

export type InsightArticleContent = { slug: string; category: string; title: string; abstract: string; readingTime: string };
export type InsightsPageContent = {
  meta: PageMeta; hero: HeroContent; introduction: SectionHeadingContent & { paragraphs: readonly string[] };
  categories: SectionHeadingContent & { items: readonly string[] };
  listing: SectionHeadingContent; articles: readonly InsightArticleContent[];
  articleChrome: { backLabel: string; eyebrow: string; body: readonly string[]; cta: CtaContent };
  cta: CtaContent;
};

const slugs = ["governance-before-capital", "informal-coordination-cost", "institutionally-legible-initiative", "logistics-as-governance", "neutral-platforms-territorial-coordination", "investment-ready-initiatives-drc"] as const;

export const insightsPageContent = {
  en: {
    meta: { title: "Insights", description: "Strategic notes on territorial economic governance, flow structuring, logistics governance, and investment readiness in Africa." },
    hero: { eyebrow: "Insights", title: "Clevones Insights", subtitle: "Strategic notes on territorial economic governance, flow structuring, logistics governance, institutional coordination, and investment-readiness in Africa.", tagline: "Governance-first perspectives on territorial economic systems." },
    introduction: { eyebrow: "Think tank", title: "Authority through structural clarity", paragraphs: ["Clevones Insights publishes strategic analysis on the governance conditions that determine whether territorial economic potential becomes durable institutional value — or remains trapped in informal coordination.", "These notes are written for institutional actors, investors, and territorial leaders who require legible frameworks before capital deployment, logistics structuring, or cross-border coordination."] },
    categories: { eyebrow: "Categories", title: "Areas of strategic analysis", description: "Clevones Insights organizes analysis across the governance domains that shape territorial economic outcomes.", items: ["Economic Governance", "Territorial Logistics", "Flow Structuring", "Compliance", "Institutional Coordination", "Investment Readiness"] },
    listing: { eyebrow: "Latest notes", title: "Strategic perspectives", description: "Institutional analysis on governance, coordination, and investment-readiness across African territorial economic systems." },
    articles: [
      { slug: slugs[0], category: "Economic Governance", title: "Why territorial potential requires governance before capital", abstract: "Capital deployed without territorial governance architecture amplifies fragmentation rather than value. This note examines why structure must precede financing in African economic systems.", readingTime: "6 min read" },
      { slug: slugs[1], category: "Compliance", title: "The hidden cost of informal coordination in African economic systems", abstract: "Informal actor networks produce short-term alignment and long-term institutional opacity. The cumulative cost — in compliance exposure, audit failure, and capital hesitation — is systematically underestimated.", readingTime: "7 min read" },
      { slug: slugs[2], category: "Flow Structuring", title: "From opportunity to institutionally legible initiative", abstract: "Opportunity identification is not initiative formation. Legibility requires documented actor mapping, governance protocols, and compliance-ready structures that institutions and investors can evaluate.", readingTime: "5 min read" },
      { slug: slugs[3], category: "Territorial Logistics", title: "Logistics is not only movement: it is governance", abstract: "Territorial logistics systems are governance architectures in motion. Movement without governed coordination produces corridor risk, institutional blind spots, and fragile supply-chain legibility.", readingTime: "6 min read" },
      { slug: slugs[4], category: "Institutional Coordination", title: "Neutral platforms and the future of territorial coordination", abstract: "Neutral coordination platforms occupy a structural position between actors without substituting them. This note explores how governed neutrality enables multi-stakeholder alignment without commercial bias.", readingTime: "8 min read" },
      { slug: slugs[5], category: "Investment Readiness", title: "Building investment-ready initiatives in the DRC", abstract: "Investment readiness in the Democratic Republic of Congo is a governance outcome — not a presentation exercise. Initiatives become fundable when documentation, actor verification, and compliance architecture are in place.", readingTime: "7 min read" },
    ],
    articleChrome: { backLabel: "← All insights", eyebrow: "Clevones Insights", body: ["Full analysis for this insight is forthcoming. Clevones Insights publishes strategic notes on territorial economic governance, institutional coordination, and investment-readiness across Africa.", "For institutional inquiries related to this topic, initiate a structured collaboration through Clevones."], cta: { title: "Initiate a strategic collaboration", description: "Submit a documented institutional inquiry related to this topic.", actions: [{ href: "/contact", label: "Initiate a strategic collaboration", variant: "secondary" }] } },
    cta: { title: "Turn governance insight into structured territorial action.", description: "Institutions, investors, and strategic partners can submit documented initiatives for governed assessment under the Clevones framework.", actions: [{ href: "/contact?intent=initiative", label: "Submit a structured initiative" }, { href: "/contact?intent=collaboration", label: "Initiate a strategic collaboration", variant: "outline" }] },
  },
  fr: {
    meta: { title: "Insights", description: "Notes stratégiques sur la gouvernance économique territoriale, la structuration des flux, la logistique et la préparation à l'investissement en Afrique." },
    hero: { eyebrow: "Insights", title: "Clevones Insights", subtitle: "Notes stratégiques sur la gouvernance économique territoriale, la structuration des flux, la gouvernance logistique, la coordination institutionnelle et la préparation à l'investissement en Afrique.", tagline: "Des perspectives centrées sur la gouvernance des systèmes économiques territoriaux." },
    introduction: { eyebrow: "Think tank", title: "L'autorité par la clarté structurelle", paragraphs: ["Clevones Insights publie des analyses stratégiques sur les conditions de gouvernance qui déterminent si le potentiel économique territorial devient une valeur institutionnelle durable — ou demeure captif de la coordination informelle.", "Ces notes s'adressent aux acteurs institutionnels, investisseurs et responsables territoriaux qui nécessitent des cadres lisibles avant le déploiement de capitaux, la structuration logistique ou la coordination transfrontalière."] },
    categories: { eyebrow: "Catégories", title: "Domaines d'analyse stratégique", description: "Clevones Insights organise ses analyses autour des domaines de gouvernance qui déterminent les résultats économiques territoriaux.", items: ["Gouvernance économique", "Logistique territoriale", "Structuration des flux", "Conformité", "Coordination institutionnelle", "Préparation à l'investissement"] },
    listing: { eyebrow: "Notes récentes", title: "Perspectives stratégiques", description: "Analyses institutionnelles sur la gouvernance, la coordination et la préparation à l'investissement dans les systèmes économiques territoriaux africains." },
    articles: [
      { slug: slugs[0], category: "Gouvernance économique", title: "Pourquoi le potentiel territorial exige la gouvernance avant le capital", abstract: "Un capital déployé sans architecture de gouvernance territoriale amplifie la fragmentation plutôt que la valeur. Cette note examine pourquoi la structure doit précéder le financement dans les systèmes économiques africains.", readingTime: "6 min de lecture" },
      { slug: slugs[1], category: "Conformité", title: "Le coût caché de la coordination informelle dans les systèmes économiques africains", abstract: "Les réseaux d'acteurs informels produisent un alignement à court terme et une opacité institutionnelle à long terme. Leur coût cumulé — exposition à la non-conformité, échec d'audit et hésitation du capital — est systématiquement sous-estimé.", readingTime: "7 min de lecture" },
      { slug: slugs[2], category: "Structuration des flux", title: "De l'opportunité à l'initiative lisible institutionnellement", abstract: "Identifier une opportunité ne constitue pas une initiative. La lisibilité exige une cartographie documentée des acteurs, des protocoles de gouvernance et des structures préparées à la conformité que les institutions et investisseurs peuvent évaluer.", readingTime: "5 min de lecture" },
      { slug: slugs[3], category: "Logistique territoriale", title: "La logistique n'est pas seulement le mouvement : elle est gouvernance", abstract: "Les systèmes logistiques territoriaux sont des architectures de gouvernance en mouvement. Le déplacement sans coordination gouvernée crée des risques de corridor, des angles morts institutionnels et une lisibilité fragile des chaînes d'approvisionnement.", readingTime: "6 min de lecture" },
      { slug: slugs[4], category: "Coordination institutionnelle", title: "Les plateformes neutres et l'avenir de la coordination territoriale", abstract: "Les plateformes de coordination neutre occupent une position structurelle entre les acteurs sans s'y substituer. Cette note examine comment la neutralité gouvernée permet l'alignement de multiples parties prenantes sans biais commercial.", readingTime: "8 min de lecture" },
      { slug: slugs[5], category: "Préparation à l'investissement", title: "Construire des initiatives prêtes à l'investissement en RDC", abstract: "La préparation à l'investissement en République Démocratique du Congo est un résultat de gouvernance — et non un exercice de présentation. Les initiatives deviennent finançables lorsque la documentation, la vérification des acteurs et l'architecture de conformité sont en place.", readingTime: "7 min de lecture" },
    ],
    articleChrome: { backLabel: "← Tous les insights", eyebrow: "Clevones Insights", body: ["L'analyse complète de cet insight sera prochainement disponible. Clevones Insights publie des notes stratégiques sur la gouvernance économique territoriale, la coordination institutionnelle et la préparation à l'investissement en Afrique.", "Pour toute demande institutionnelle relative à ce sujet, initiez une collaboration structurée avec Clevones."], cta: { title: "Initier une collaboration stratégique", description: "Soumettez une demande institutionnelle documentée relative à ce sujet.", actions: [{ href: "/collaboration", label: "Initier une collaboration stratégique", variant: "secondary" }] } },
    cta: { title: "Transformer l'analyse de gouvernance en action territoriale structurée.", description: "Les institutions, investisseurs et partenaires stratégiques peuvent soumettre des initiatives documentées à une évaluation gouvernée selon le cadre Clevones.", actions: [{ href: "/collaboration?intent=initiative", label: "Soumettre une initiative structurée" }, { href: "/collaboration?intent=collaboration", label: "Initier une collaboration stratégique", variant: "outline" }] },
  },
} as const satisfies LocalizedPageContent<InsightsPageContent>;
