import type { AgentDefinition } from "@/lib/agentic/types";

/**
 * Static worker catalog. IDs are stable. No vendor SDK is imported here.
 * Finance/commercial/DMS agents are internal workers with tool allowlists —
 * they do not move money, send customer mail, or export confidential files.
 */
export const DEFAULT_AGENT_CATALOG: readonly AgentDefinition[] = [
  {
    id: "CLEVONE_FINANCE_AGENT",
    displayName: "CLEVONE Finance Agent",
    provider: "internal",
    model: null,
    capabilities: ["extract", "classify", "reconcile"],
    allowedTools: [
      "payments.read",
      "payments.reconcile.recommend",
      "documents.read.metadata",
    ],
    permissions: ["finance.recommend", "finance.read"],
    estimatedCostPerTask: 2,
    priority: 10,
    availability: "available",
    status: "available",
    limits: {
      maxRisk: "MEDIUM",
      maxConcurrency: 4,
      requiresHumanAboveRisk: "MEDIUM",
      allowConfidentialContent: true,
    },
    trustLevel: "high",
  },
  {
    id: "CLEVONE_COMMERCIAL_AGENT",
    displayName: "CLEVONE Commercial Agent",
    provider: "internal",
    model: null,
    capabilities: ["classify", "draft", "crm", "summarize"],
    allowedTools: ["crm.read", "crm.draft", "search.internal"],
    permissions: ["commercial.draft", "crm.read"],
    estimatedCostPerTask: 3,
    priority: 20,
    availability: "available",
    status: "available",
    limits: {
      maxRisk: "MEDIUM",
      maxConcurrency: 4,
      requiresHumanAboveRisk: "MEDIUM",
      allowConfidentialContent: true,
    },
    trustLevel: "medium",
  },
  {
    id: "CLEVONE_DMS_AGENT",
    displayName: "CLEVONE DMS Agent",
    provider: "internal",
    model: null,
    capabilities: ["classify", "extract", "search", "documents"],
    allowedTools: [
      "documents.read.metadata",
      "documents.classify",
      "documents.search",
    ],
    permissions: ["documents.read", "documents.classify"],
    estimatedCostPerTask: 2,
    priority: 15,
    availability: "available",
    status: "available",
    limits: {
      maxRisk: "MEDIUM",
      maxConcurrency: 4,
      requiresHumanAboveRisk: "MEDIUM",
      allowConfidentialContent: true,
    },
    trustLevel: "high",
  },
  {
    id: "CLEVONE_ADMIN_AGENT",
    displayName: "CLEVONE Admin Agent",
    provider: "internal",
    model: null,
    capabilities: ["admin_ops", "search", "summarize"],
    allowedTools: ["audit.read", "x200.status.read"],
    permissions: ["admin.read"],
    estimatedCostPerTask: 1,
    priority: 30,
    availability: "available",
    status: "available",
    limits: {
      maxRisk: "LOW",
      maxConcurrency: 2,
      requiresHumanAboveRisk: "LOW",
      allowConfidentialContent: true,
    },
    trustLevel: "high",
  },
  {
    id: "CURSOR_DEV_WORKER",
    displayName: "Cursor Development Worker",
    provider: "cursor",
    model: "cursor-agent",
    capabilities: ["code", "review"],
    allowedTools: ["git.read", "ci.read", "repo.edit.authorized"],
    permissions: ["dev.implement"],
    estimatedCostPerTask: 8,
    priority: 5,
    availability: "available",
    status: "available",
    limits: {
      maxRisk: "HIGH",
      maxConcurrency: 1,
      requiresHumanAboveRisk: "HIGH",
      allowConfidentialContent: true,
    },
    trustLevel: "high",
  },
  {
    id: "GROK_WORKER",
    displayName: "Grok Worker",
    provider: "grok",
    model: "grok-4",
    capabilities: ["classify", "summarize", "draft", "extract"],
    allowedTools: ["search.internal"],
    permissions: ["llm.infer"],
    estimatedCostPerTask: 6,
    priority: 40,
    availability: "available",
    status: "available",
    limits: {
      maxRisk: "LOW",
      maxConcurrency: 2,
      requiresHumanAboveRisk: "LOW",
      allowConfidentialContent: false,
    },
    trustLevel: "medium",
  },
  {
    id: "OPENAI_WORKER",
    displayName: "OpenAI Worker",
    provider: "openai",
    model: "gpt-5",
    capabilities: ["classify", "summarize", "draft", "extract"],
    allowedTools: ["search.internal"],
    permissions: ["llm.infer"],
    estimatedCostPerTask: 7,
    priority: 45,
    availability: "available",
    status: "available",
    limits: {
      maxRisk: "LOW",
      maxConcurrency: 2,
      requiresHumanAboveRisk: "LOW",
      allowConfidentialContent: false,
    },
    trustLevel: "medium",
  },
];
